app:
  scheduling:
    enabled: true
    exchange:
      cron: "*/5 * * * * *"
      zone: UTC
    gift:
      cron: "30 */10 * * * *"
      zone: UTC
    visit-memo:
      cron: "59 */10 * * * *"
      zone: UTC
